/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_supermercado;
/**
 *
 * @author MEDAC
 */
public class BuscadorClientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BuscadorClientes.class.getName());

    /**
     * Creates new form BuscadorClientes
     */
    public BuscadorClientes() {
        initComponents();
        // --- COPIA Y PEGA ESTE BLOQUE ENTERO ---
// Pégalo en tu pestaña "Source", dentro del constructor
// (justo DESPUÉS de la línea "initComponents();")

try {
// --- 1. ¡CAMBIA ESTE NOMBRE! ---
// Pon el "Variable Name" de tu JLabel (el que viste en "Properties" > "Code")
javax.swing.JLabel labelDelIcono = jLabel2; // <--- ¡¡CAMBIA 'jLabel1' POR EL TUYO!!

// --- 2. Obtenemos el icono gigante que le pusiste en el "Design"
javax.swing.ImageIcon iconoGrande = (javax.swing.ImageIcon) labelDelIcono.getIcon();

if (iconoGrande != null) {
    // --- 3. Sacamos la imagen de dentro
    java.awt.Image img = iconoGrande.getImage();

    // --- 4. ¡CAMBIA ESTE TAMAÑO! ---
    // Pon el ancho y alto que tú quieras (ej: 32x32 píxeles)
    int anchoDeseado = 32;
    int altoDeseado = 32;

    // --- 5. Redimensionamos la imagen
    java.awt.Image imgRedimensionada = img.getScaledInstance(anchoDeseado, altoDeseado, java.awt.Image.SCALE_SMOOTH);

    // --- 6. Creamos un nuevo icono con la imagen pequeña
    javax.swing.ImageIcon iconoPequeño = new javax.swing.ImageIcon(imgRedimensionada);

    // --- 7. Ponemos el icono PEQUEÑO de vuelta en el JLabel
    labelDelIcono.setIcon(iconoPequeño);
}


} catch (Exception e) {
System.out.println("Error al redimensionar icono: " + e.getMessage());
}
// --- FIN DEL BLOQUE PARA COPIAR ---
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        BC_acceder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BC_name = new javax.swing.JTextField();
        BC_dni = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.columnWeights = new double[] {5.0};
        layout.rowWeights = new double[] {0.0};
        getContentPane().setLayout(layout);

        BC_acceder.setBackground(new java.awt.Color(51, 153, 255));
        BC_acceder.setText("ACCEDER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 1, 0);
        getContentPane().add(BC_acceder, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("BÚSQUEDA DE CLIENTES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 1, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\MEDAC\\Documents\\NetBeansProjects\\SUPERMERCADO_INTERFACES\\src\\supermarketresouerces\\icon_persona.jpg")); // NOI18N
        jLabel2.setText("INTRODUCE TU NOMBRE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 1, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("INTRODUCE TU DNI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 1, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        BC_name.setText("Intoducir DNI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 1, 0);
        getContentPane().add(BC_name, gridBagConstraints);

        BC_dni.setText("Introducir nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 1, 0);
        getContentPane().add(BC_dni, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BuscadorClientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BC_acceder;
    private javax.swing.JTextField BC_dni;
    private javax.swing.JTextField BC_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
