package com.mycompany.proyecto_supermercado;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import com.mycompany.app.Cliente;
import com.mycompany.app.Empleado;
import com.mycompany.dao.ClienteDAO;
import com.mycompany.dao.EmpleadoDAO;
import com.mycompany.proyecto_supermercado.BuscadorCliente;
import com.mycompany.proyecto_supermercado.Gestion_Tablas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author MEDAC
 */
public class Menu_empleados extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu_empleados.class.getName());

    /**
     * Creates new form Login
     */
    public Menu_empleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btncrearcliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnbuscarempleado = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        btnVerEmpleados = new javax.swing.JButton();
        Crear_empleado = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        btnverclientes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtbuscar1 = new javax.swing.JTextField();
        btnborrarcliente = new javax.swing.JButton();
        btnbuscarcliente = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtApellidos1 = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        txtDn = new javax.swing.JTextField();
        txtTelefono1 = new javax.swing.JTextField();
        txtEmail1 = new javax.swing.JTextField();
        txtDireccion1 = new javax.swing.JTextField();
        txtCiudad1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnborrarempleado = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        actualizarempleado = new javax.swing.JButton();
        actualizarcliente = new javax.swing.JButton();
        txtIdCliente = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("MENÚ EMPLEADOS");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario.png"))); // NOI18N
        jLabel22.setText("Usuario");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha-izquierda.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAtras(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(364, 364, 364)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel22)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Información", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 18)))); // NOI18N

        btncrearcliente.setBackground(new java.awt.Color(153, 255, 153));
        btncrearcliente.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btncrearcliente.setText("Crear cliente");
        btncrearcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearclienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Buscar o borrar por ID:");

        btnbuscarempleado.setBackground(new java.awt.Color(153, 255, 153));
        btnbuscarempleado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnbuscarempleado.setText("Buscar empleado");
        btnbuscarempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarempleadoActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Para ver todos los empleados, pulsa aquí");

        txtbuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtbuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });

        btnVerEmpleados.setBackground(new java.awt.Color(153, 255, 153));
        btnVerEmpleados.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnVerEmpleados.setText("Ver empleados");
        btnVerEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEmpleadosActionPerformed(evt);
            }
        });

        Crear_empleado.setBackground(new java.awt.Color(153, 255, 153));
        Crear_empleado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Crear_empleado.setText("Crear empleado");
        Crear_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_empleadoActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Para ver todos los clientes, pulsa aquí");

        btnverclientes.setBackground(new java.awt.Color(153, 255, 153));
        btnverclientes.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnverclientes.setText("Ver clientes");
        btnverclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverclientesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Buscar o borrar cliente por ID:");

        txtbuscar1.setBackground(new java.awt.Color(255, 255, 255));
        txtbuscar1.setForeground(new java.awt.Color(0, 0, 0));

        btnborrarcliente.setBackground(new java.awt.Color(153, 255, 153));
        btnborrarcliente.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnborrarcliente.setText("Borrar cliente");
        btnborrarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarclienteActionPerformed(evt);
            }
        });

        btnbuscarcliente.setBackground(new java.awt.Color(153, 255, 153));
        btnbuscarcliente.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnbuscarcliente.setText("Buscar cliente ");
        btnbuscarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarclienteActionPerformed(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setText("Nombre:");

        txtApellidos.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidos.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setText("Apellidos:");

        txtDni.setBackground(new java.awt.Color(255, 255, 255));
        txtDni.setForeground(new java.awt.Color(0, 0, 0));
        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });

        jLabel10.setText("Dni:");

        txtSalario.setBackground(new java.awt.Color(255, 255, 255));
        txtSalario.setForeground(new java.awt.Color(0, 0, 0));
        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });

        jLabel11.setText("Salario:");

        txtApellidos1.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidos1.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidos1ActionPerformed(evt);
            }
        });

        txtNombre1.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre1.setForeground(new java.awt.Color(0, 0, 0));

        txtDn.setBackground(new java.awt.Color(255, 255, 255));
        txtDn.setForeground(new java.awt.Color(0, 0, 0));
        txtDn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDnActionPerformed(evt);
            }
        });

        txtTelefono1.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono1.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefono1ActionPerformed(evt);
            }
        });

        txtEmail1.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail1.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail1ActionPerformed(evt);
            }
        });

        txtDireccion1.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion1.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccion1ActionPerformed(evt);
            }
        });

        txtCiudad1.setBackground(new java.awt.Color(255, 255, 255));
        txtCiudad1.setForeground(new java.awt.Color(0, 0, 0));
        txtCiudad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiudad1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Nombre:");

        jLabel13.setText("Apellidos:");

        jLabel14.setText("Dni:");

        jLabel15.setText("Telefono:");

        jLabel16.setText("Email:");

        jLabel17.setText("Dirección:");

        jLabel18.setText("Ciudad:");

        btnborrarempleado.setBackground(new java.awt.Color(153, 255, 153));
        btnborrarempleado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnborrarempleado.setText("Borrar empleado");
        btnborrarempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarempleadoActionPerformed(evt);
            }
        });

        jLabel19.setText("ID:");

        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setForeground(new java.awt.Color(0, 0, 0));

        actualizarempleado.setBackground(new java.awt.Color(153, 255, 153));
        actualizarempleado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        actualizarempleado.setText("Actualizar empleado");
        actualizarempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarempleadoActionPerformed(evt);
            }
        });

        actualizarcliente.setBackground(new java.awt.Color(153, 255, 153));
        actualizarcliente.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        actualizarcliente.setText("Actualizar cliente");
        actualizarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarclienteActionPerformed(evt);
            }
        });

        txtIdCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtIdCliente.setForeground(new java.awt.Color(0, 0, 0));

        jLabel20.setText("ID:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel21)
                .addGap(65, 65, 65)
                .addComponent(actualizarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btncrearcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(43, 43, 43)
                        .addComponent(txtbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(31, 31, 31)
                        .addComponent(btnverclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(728, 728, 728))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnborrarempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbuscarempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(btnborrarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnbuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel10)
                        .addGap(39, 39, 39)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(37, 37, 37)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(actualizarempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Crear_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)))
                            .addComponent(jLabel16)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDn)
                            .addComponent(txtEmail1)
                            .addComponent(txtDireccion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(357, 357, 357))
                    .addComponent(txtCiudad1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelefono1)
                    .addComponent(txtApellidos1)
                    .addComponent(txtNombre1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(369, 369, 369))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtApellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtDn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addComponent(txtDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Crear_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(actualizarempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtCiudad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncrearcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actualizarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnborrarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnbuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnbuscarempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnborrarempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVerEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(btnverclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Facturas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 18)))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("Nombre cliente: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("Sociedad de la empresa:");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "S.L.", "S.A.", "Autónomo" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("CIF empresa:");

        jButton7.setBackground(new java.awt.Color(153, 255, 153));
        jButton7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton7.setText("REALIZAR FACTURA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(jComboBox1, 0, 346, Short.MAX_VALUE)
                            .addComponent(jTextField4)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1647, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAtras(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAtras
          Menu me = new Menu();
          me.setVisible(true);
          dispose();
    }//GEN-LAST:event_BotonAtras

    private void btncrearclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearclienteActionPerformed
          try {
        // 1️⃣ Leer datos del formulario
        String nombre = txtNombre1.getText();
        String apellidos = txtApellidos1.getText();
        String dni = txtDn.getText();
        String telefono = txtTelefono1.getText();
        String email = txtEmail1.getText();
        String direccion = txtDireccion1.getText();
        String ciudad = txtCiudad1.getText();

        // Validación mínima
        if (nombre.isEmpty() || dni.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nombre y DNI son obligatorios");
            return;
        }

        // 2️⃣ Crear objeto Cliente
        Cliente cliente = new Cliente(
                0, // id autoincrement
                nombre,
                apellidos,
                dni,
                telefono,
                email,
                direccion,
                ciudad
        );

        // 3️⃣ Llamar al DAO
        ClienteDAO dao = new ClienteDAO();
        dao.insertar(cliente);

        // 4️⃣ Confirmación
        JOptionPane.showMessageDialog(null, "Cliente guardado correctamente");

        // 5️⃣ Limpiar campos
        txtNombre1.setText("");
        txtApellidos1.setText("");
        txtDn.setText("");
        txtTelefono1.setText("");
        txtEmail1.setText("");
        txtDireccion1.setText("");
        txtCiudad1.setText("");

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error al guardar cliente: " + ex.getMessage());
    }
    }//GEN-LAST:event_btncrearclienteActionPerformed

    private void btnbuscarempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarempleadoActionPerformed
       try {
        // Obtenemos el ID desde el JTextField
        int id = Integer.parseInt(txtbuscar.getText().trim());

        // Creamos DAO y buscamos el empleado
        EmpleadoDAO dao = new EmpleadoDAO();
        Empleado emp = dao.buscarPorId(id);

        if (emp != null) {
            // Si se encuentra, mostramos los datos
            String texto = "ID: " + emp.getId() +
                           "\nNombre: " + emp.getNombre() + " " + emp.getApellidos() +
                           "\nDNI: " + emp.getDni() +
                           "\nSalario: " + emp.getSalario();

            JOptionPane.showMessageDialog(null, texto, "Empleado Encontrado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Si no se encuentra
            JOptionPane.showMessageDialog(null, "No se encontró ningún empleado con ID " + id,
                                          "Empleado No Encontrado", JOptionPane.WARNING_MESSAGE);
        }

    } catch (NumberFormatException ex) {
        // Si no se ingresa un número válido
        JOptionPane.showMessageDialog(null, "Por favor ingresa un ID válido", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        // Otros errores (base de datos, conexión, etc.)
        JOptionPane.showMessageDialog(null, "Error al buscar empleado:\n" + ex.getMessage(),
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnbuscarempleadoActionPerformed

    private void btnVerEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEmpleadosActionPerformed

 
    try {
        EmpleadoDAO dao = new EmpleadoDAO();
        List<Empleado> lista = dao.listar();

        StringBuilder texto = new StringBuilder();

        for (Empleado emp : lista) {
            texto.append("ID: ").append(emp.getId())
                 .append(" | ")
                 .append(emp.getNombre())
                 .append(" ")
                 .append(emp.getApellidos())
                 .append(" | DNI: ")
                 .append(emp.getDni())
                 .append(" | Salario: ")
                 .append(emp.getSalario())
                 .append("\n");
        }

        JOptionPane.showMessageDialog(null, texto.toString());

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }


    }//GEN-LAST:event_btnVerEmpleadosActionPerformed

    private void Crear_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_empleadoActionPerformed
     
    try {
        // 1️⃣ Leer datos del formulario
        String nombre = txtNombre.getText();
        String apellidos = txtApellidos.getText();
        String dni = txtDni.getText();
        double salario = Double.parseDouble(txtSalario.getText());

        // 2️⃣ Crear objeto Empleado
        Empleado emp = new Empleado(
                0,          // id (no importa si es autoincrement)
                nombre,
                apellidos,
                dni,
                salario
        );

        // 3️⃣ Llamar al DAO
        EmpleadoDAO dao = new EmpleadoDAO();
        dao.insertar(emp);

        // 4️⃣ Confirmación
        JOptionPane.showMessageDialog(null, "Empleado guardado correctamente");

        // 5️⃣ Limpiar campos (opcional)
        txtNombre.setText("");
        txtApellidos.setText("");
        txtDni.setText("");
        txtSalario.setText("");

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error al guardar empleado: " + ex.getMessage());
    }


    }//GEN-LAST:event_Crear_empleadoActionPerformed

    private void btnverclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverclientesActionPerformed
      try {
    ClienteDAO dao = new ClienteDAO();
    List<Cliente> lista = dao.listar();

    StringBuilder texto = new StringBuilder();

    if (lista.isEmpty()) {
        texto.append("No hay clientes registrados.\n");
    } else {
        for (Cliente c : lista) {
            texto.append("ID: ").append(c.getId()).append("\n")
                 .append("Nombre: ").append(c.getNombre()).append(" ").append(c.getApellidos()).append("\n")
                 .append("DNI: ").append(c.getDni()).append("\n")
                 .append("Teléfono: ").append(c.getTelefono()).append("\n")
                 .append("Email: ").append(c.getEmail()).append("\n")
                 .append("Dirección: ").append(c.getDireccion()).append("\n")
                 .append("Ciudad: ").append(c.getCiudad()).append("\n")
                 .append("----------------------------------\n");
        }
    }

    // Mostramos en un JOptionPane en lugar de txtAreaClientes
    JOptionPane.showMessageDialog(null, texto.toString(), "Lista de Clientes", JOptionPane.INFORMATION_MESSAGE);

} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, "Error al cargar clientes:\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnverclientesActionPerformed

    private void btnborrarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarclienteActionPerformed
       try {
        // Obtenemos el ID desde el JTextField
        int id = Integer.parseInt(txtbuscar1.getText().trim());

        // Creamos DAO y borramos el cliente
        ClienteDAO dao = new ClienteDAO();
        Cliente c = dao.buscarPorId(id); // primero verificamos si existe

        if (c != null) {
            int confirmar = JOptionPane.showConfirmDialog(null,
                    "¿Seguro que quieres eliminar al cliente " + c.getNombre() + " " + c.getApellidos() + "?",
                    "Confirmar Borrado",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (confirmar == JOptionPane.YES_OPTION) {
                dao.eliminar(id); // borramos el cliente
                JOptionPane.showMessageDialog(null, "Cliente eliminado correctamente",
                                              "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            // Si no se encuentra el cliente
            JOptionPane.showMessageDialog(null, "No se encontró ningún cliente con ID " + id,
                                          "Cliente No Encontrado", JOptionPane.WARNING_MESSAGE);
        }

    } catch (NumberFormatException ex) {
        // Si el ID ingresado no es un número
        JOptionPane.showMessageDialog(null, "Por favor ingresa un ID válido", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        // Otros errores (BD, conexión, etc.)
        JOptionPane.showMessageDialog(null, "Error al borrar cliente:\n" + ex.getMessage(),
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnborrarclienteActionPerformed

    private void btnbuscarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarclienteActionPerformed
      try {
        // Obtenemos el ID desde el JTextField
        int id = Integer.parseInt(txtbuscar1.getText().trim());

        // Creamos DAO y buscamos el cliente
        ClienteDAO dao = new ClienteDAO();
        Cliente c = dao.buscarPorId(id);

        if (c != null) {
            // Si se encuentra, mostramos los datos
            StringBuilder texto = new StringBuilder();
            texto.append("ID: ").append(c.getId()).append("\n")
                 .append("Nombre: ").append(c.getNombre()).append(" ").append(c.getApellidos()).append("\n")
                 .append("DNI: ").append(c.getDni()).append("\n")
                 .append("Teléfono: ").append(c.getTelefono()).append("\n")
                 .append("Email: ").append(c.getEmail()).append("\n")
                 .append("Dirección: ").append(c.getDireccion()).append("\n")
                 .append("Ciudad: ").append(c.getCiudad());

            JOptionPane.showMessageDialog(null, texto.toString(), "Cliente Encontrado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Si no se encuentra
            JOptionPane.showMessageDialog(null, "No se encontró ningún cliente con ID " + id,
                                          "Cliente No Encontrado", JOptionPane.WARNING_MESSAGE);
        }

    } catch (NumberFormatException ex) {
        // Si no se ingresa un número válido
        JOptionPane.showMessageDialog(null, "Por favor ingresa un ID válido", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        // Otros errores (base de datos, conexión, etc.)
        JOptionPane.showMessageDialog(null, "Error al buscar cliente:\n" + ex.getMessage(),
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnbuscarclienteActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtApellidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidos1ActionPerformed

    private void txtDnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDnActionPerformed

    private void txtTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefono1ActionPerformed

    private void txtEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail1ActionPerformed

    private void txtDireccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccion1ActionPerformed

    private void txtCiudad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudad1ActionPerformed

    private void btnborrarempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarempleadoActionPerformed
        try {
        // Obtenemos el ID desde el JTextField
        int id = Integer.parseInt(txtbuscar.getText().trim());

        // Creamos DAO y buscamos el empleado primero
        EmpleadoDAO dao = new EmpleadoDAO();
        Empleado emp = dao.buscarPorId(id);

        if (emp != null) {
            int confirmar = JOptionPane.showConfirmDialog(null,
                    "¿Seguro que quieres eliminar al empleado " + emp.getNombre() + " " + emp.getApellidos() + "?",
                    "Confirmar Borrado",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (confirmar == JOptionPane.YES_OPTION) {
                dao.borrar(id); // borramos el empleado
                JOptionPane.showMessageDialog(null, "Empleado eliminado correctamente",
                                              "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            // Si no se encuentra el empleado
            JOptionPane.showMessageDialog(null, "No se encontró ningún empleado con ID " + id,
                                          "Empleado No Encontrado", JOptionPane.WARNING_MESSAGE);
        }

    } catch (NumberFormatException ex) {
        // Si el ID ingresado no es un número
        JOptionPane.showMessageDialog(null, "Por favor ingresa un ID válido", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        // Otros errores (BD, conexión, etc.)
        JOptionPane.showMessageDialog(null, "Error al borrar empleado:\n" + ex.getMessage(),
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnborrarempleadoActionPerformed

    private void actualizarempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarempleadoActionPerformed
         try {
        int id = Integer.parseInt(txtId.getText().trim());
        EmpleadoDAO dao = new EmpleadoDAO();
        Empleado emp = dao.buscarPorId(id);

        if (emp != null) {
            // Llenamos los campos con los datos actuales
            txtNombre.setText(emp.getNombre());
            txtApellidos.setText(emp.getApellidos());
            txtDni.setText(emp.getDni());
            txtSalario.setText(String.valueOf(emp.getSalario()));
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró ningún empleado con ID " + id,
                                          "Empleado No Encontrado", JOptionPane.WARNING_MESSAGE);
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Por favor ingresa un ID válido", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error al buscar empleado:\n" + ex.getMessage(),
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_actualizarempleadoActionPerformed

    private void actualizarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarclienteActionPerformed
        try {
        // Obtenemos el ID del cliente a actualizar
        int id = Integer.parseInt(txtIdCliente.getText().trim());

        // Obtenemos los datos modificados de los campos
        String nombre = txtNombre1.getText().trim();
        String apellidos = txtApellidos1.getText().trim();
        String dni = txtDn.getText().trim();
        String telefono = txtTelefono1.getText().trim();
        String email = txtEmail1.getText().trim();
        String direccion = txtDireccion1.getText().trim();
        String ciudad = txtCiudad1.getText().trim();

        // Creamos un objeto Cliente con los nuevos datos
        Cliente c = new Cliente(id, nombre, apellidos, dni, telefono, email, direccion, ciudad);

        // Actualizamos en la base de datos
        ClienteDAO dao = new ClienteDAO();
        dao.actualizar(c);

        JOptionPane.showMessageDialog(null, "Cliente actualizado correctamente",
                                      "Éxito", JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Por favor ingresa un ID válido", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error al actualizar cliente:\n" + ex.getMessage(),
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_actualizarclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu_empleados().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Crear_empleado;
    private javax.swing.JButton actualizarcliente;
    private javax.swing.JButton actualizarempleado;
    private javax.swing.JButton btnVerEmpleados;
    private javax.swing.JButton btnborrarcliente;
    private javax.swing.JButton btnborrarempleado;
    private javax.swing.JButton btnbuscarcliente;
    private javax.swing.JButton btnbuscarempleado;
    private javax.swing.JButton btncrearcliente;
    private javax.swing.JButton btnverclientes;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtApellidos1;
    private javax.swing.JTextField txtCiudad1;
    private javax.swing.JTextField txtDireccion1;
    private javax.swing.JTextField txtDn;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtbuscar1;
    // End of variables declaration//GEN-END:variables
}
