/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_supermercado;

import javax.swing.JFrame;

/**
 *
 * @author joses
 */
public class Ventana_lacteos extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_lacteos
     */
    public Ventana_lacteos() {
    
        initComponents();
        setLocationRelativeTo(null);
        cargarDatosStock();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblStockYogur = new javax.swing.JLabel();
        lblStockLeche = new javax.swing.JLabel();
        lblStockQueso = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("LÁCTEOS");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha-izquierda.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAtras(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cestaaaaas.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel9)
                .addGap(433, 433, 433)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jLabel9))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel1))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Lácteos disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14)))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yogur-griego.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leche.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarta-de-queso.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        lblStockYogur.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblStockYogur.setForeground(new java.awt.Color(153, 255, 153));
        lblStockYogur.setText("5 UNIDADES YOGUR GRIEGO DISPONIBLES");

        lblStockLeche.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblStockLeche.setForeground(new java.awt.Color(255, 51, 51));
        lblStockLeche.setText("0 STOCK LECHE");

        lblStockQueso.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblStockQueso.setForeground(new java.awt.Color(255, 255, 204));
        lblStockQueso.setText("SIN EXISTENCIAS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(244, 244, 244))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblStockYogur)
                        .addGap(144, 144, 144)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(238, 238, 238)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblStockLeche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStockQueso)))
                .addGap(99, 99, 99))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStockYogur)
                    .addComponent(lblStockLeche)
                    .addComponent(lblStockQueso))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel8.setText("El stock de lácteos puede variar según días y semanas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(58, 366, 51, 276);
        jPanel4.add(jLabel8, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAtras(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAtras
        Gestor_Stock gs = new Gestor_Stock();
        gs.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonAtras

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        // Producto: Leche Entera (ID 1)
        com.mycompany.dao.ProductoDAO dao = new com.mycompany.dao.ProductoDAO();
        com.mycompany.app.Carrito carrito = com.mycompany.app.Carrito.getInstancia();

        try {
            com.mycompany.app.Producto producto = dao.buscarPorId(1);

            if (producto != null) {
                if (carrito.getCantidadProducto(1) + 1 > producto.getStock()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "¡Stock agotado!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }

                carrito.anadirProducto(producto, 1);
                cargarDatosStock();
                javax.swing.JOptionPane.showMessageDialog(this, "Añadido al carrito: " + producto.getNombre());
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error de conexión", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // Producto: Yogur Natural (ID 2)
        com.mycompany.dao.ProductoDAO dao = new com.mycompany.dao.ProductoDAO();
        com.mycompany.app.Carrito carrito = com.mycompany.app.Carrito.getInstancia();

        try {
            com.mycompany.app.Producto producto = dao.buscarPorId(2);

            if (producto != null) {
                if (carrito.getCantidadProducto(2) + 1 > producto.getStock()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "¡Stock agotado!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }

                carrito.anadirProducto(producto, 1);
                cargarDatosStock();
                javax.swing.JOptionPane.showMessageDialog(this, "Añadido al carrito: " + producto.getNombre());
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error de conexión", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // Producto: Queso Curado (ID 3)
com.mycompany.dao.ProductoDAO dao = new com.mycompany.dao.ProductoDAO();
com.mycompany.app.Carrito carrito = com.mycompany.app.Carrito.getInstancia();

try {
    com.mycompany.app.Producto producto = dao.buscarPorId(3);
    
    if (producto != null) {
        if (carrito.getCantidadProducto(3) + 1 > producto.getStock()) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Stock agotado!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        carrito.anadirProducto(producto, 1);
        cargarDatosStock();
        javax.swing.JOptionPane.showMessageDialog(this, "Añadido al carrito: " + producto.getNombre());
    }
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error de conexión", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
       com.mycompany.app.Carrito carrito = com.mycompany.app.Carrito.getInstancia();

        if (carrito.getListaElementos().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "La cesta está vacía. ¡Añade productos primero!");
        } else {
            //Construimos el texto del ticket
            StringBuilder mensaje = new StringBuilder();
            mensaje.append("=== TU COMPRA ACTUAL ===\n\n");

            for (com.mycompany.app.Carrito.ElementoCarrito item : carrito.getListaElementos()) {
                mensaje.append("• ").append(item.getProducto().getNombre())
                        .append("  (x").append(item.getCantidad()).append(")")
                        .append("  ->  ").append(String.format("%.2f", item.getImporteTotal())).append("€\n");
            }

            mensaje.append("\n========================\n");
            mensaje.append("TOTAL: ").append(String.format("%.2f", carrito.calcularTotal())).append("€");

            //Definimos los botones que queremos que salgan
            Object[] botones = {"Ir a Pagar", "Seguir Comprando"};

            //Mostramos la ventana con opciones
            int opcionElegida = javax.swing.JOptionPane.showOptionDialog(
                    this,
                    mensaje.toString(),
                    "Revisar Cesta",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null,
                    botones,
                    botones[1] // Botón seleccionado por defecto
            );

            //Actuamos según lo que haya pulsado
            if (opcionElegida == 0) {
         
                new Ventana_pago().setVisible(true);
                this.dispose();
            }
            
        }
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_lacteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_lacteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_lacteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_lacteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_lacteos().setVisible(true);
            }
        });

    }

    private void cargarDatosStock() {
    com.mycompany.dao.ProductoDAO dao = new com.mycompany.dao.ProductoDAO();
    com.mycompany.app.Carrito carrito = com.mycompany.app.Carrito.getInstancia();
    
    try {
        // --- PRODUCTO ID 1: LECHE ---
        com.mycompany.app.Producto p1 = dao.buscarPorId(1);
        if (p1 != null) {
            int stockReal = p1.getStock() - carrito.getCantidadProducto(1);
            lblStockLeche.setText(p1.getNombre() + " - Stock: " + stockReal);
            
            if (stockReal <= 0) {
                lblStockLeche.setText("AGOTADO");
                lblStockLeche.setForeground(java.awt.Color.RED);
            } else {
                lblStockLeche.setForeground(java.awt.Color.BLACK);
            }
        }

        // --- PRODUCTO ID 2: YOGUR ---
        com.mycompany.app.Producto p2 = dao.buscarPorId(2);
        if (p2 != null) {
            int stockReal = p2.getStock() - carrito.getCantidadProducto(2);
            lblStockYogur.setText(p2.getNombre() + " - Stock: " + stockReal);
            
            if (stockReal <= 0) {
                lblStockYogur.setText("AGOTADO");
                lblStockYogur.setForeground(java.awt.Color.RED);
            } else {
                lblStockYogur.setForeground(java.awt.Color.BLACK);
            }
        }

        // --- PRODUCTO ID 3: QUESO ---
        com.mycompany.app.Producto p3 = dao.buscarPorId(3);
        if (p3 != null) {
            int stockReal = p3.getStock() - carrito.getCantidadProducto(3);
            lblStockQueso.setText(p3.getNombre() + " - Stock: " + stockReal);
            
            if (stockReal <= 0) {
                lblStockQueso.setText("AGOTADO");
                lblStockQueso.setForeground(java.awt.Color.RED);
            } else {
                lblStockQueso.setForeground(java.awt.Color.BLACK);
            }
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar los stocks: " + e.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblStockLeche;
    private javax.swing.JLabel lblStockQueso;
    private javax.swing.JLabel lblStockYogur;
    // End of variables declaration//GEN-END:variables
}
