/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_supermercado;

/**
 *
 * @author joses
 */
public class Ventana_carnes extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_carnes
     */
    public Ventana_carnes() {
        initComponents();
        setLocationRelativeTo(null);
        cargarDatosStock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblStockTernera = new javax.swing.JLabel();
        lblStockPollo = new javax.swing.JLabel();
        lblStockHamburguesa = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("CARNES");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha-izquierda.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAtras(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cestaaaaas.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(363, 363, 363)
                .addComponent(jButton2)
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Carnes disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 14)))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carne(1).png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carne(2).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chuleta.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        lblStockTernera.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStockTernera.setForeground(new java.awt.Color(204, 0, 0));
        lblStockTernera.setText("0 STOCK HAMBURGUESAS");

        lblStockPollo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStockPollo.setForeground(new java.awt.Color(102, 255, 102));
        lblStockPollo.setText("20 KG FILETES DISPONIBLES");

        lblStockHamburguesa.setBackground(new java.awt.Color(0, 0, 0));
        lblStockHamburguesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStockHamburguesa.setForeground(new java.awt.Color(102, 255, 102));
        lblStockHamburguesa.setText("5 CHULETONES DISPONIBLES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblStockTernera)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(276, 276, 276)
                        .addComponent(jLabel4)
                        .addGap(91, 91, 91))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(lblStockPollo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStockHamburguesa)
                        .addGap(58, 58, 58))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStockTernera)
                    .addComponent(lblStockPollo)
                    .addComponent(lblStockHamburguesa))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 0, 0));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel8.setText("El stock de carnes puede ir variando según días y semanas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(47, 341, 43, 255);
        jPanel5.add(jLabel8, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAtras(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAtras
        Gestor_Stock gs = new Gestor_Stock();
        gs.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonAtras

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        com.mycompany.dao.ProductoDAO dao = new com.mycompany.dao.ProductoDAO();
        com.mycompany.app.Carrito carrito = com.mycompany.app.Carrito.getInstancia();
        try {
            com.mycompany.app.Producto p = dao.buscarPorId(4);
            if (p != null) {
                if (carrito.getCantidadProducto(4) + 1 > p.getStock()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "¡Stock agotado!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
                carrito.anadirProducto(p, 1);
                cargarDatosStock();
                javax.swing.JOptionPane.showMessageDialog(this, "Añadido: " + p.getNombre());
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        com.mycompany.dao.ProductoDAO dao = new com.mycompany.dao.ProductoDAO();
        com.mycompany.app.Carrito carrito = com.mycompany.app.Carrito.getInstancia();
        try {
            com.mycompany.app.Producto p = dao.buscarPorId(5);
            if (p != null) {
                if (carrito.getCantidadProducto(5) + 1 > p.getStock()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "¡Stock agotado!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
                carrito.anadirProducto(p, 1);
                cargarDatosStock();
                javax.swing.JOptionPane.showMessageDialog(this, "Añadido: " + p.getNombre());
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        com.mycompany.dao.ProductoDAO dao = new com.mycompany.dao.ProductoDAO();
        com.mycompany.app.Carrito carrito = com.mycompany.app.Carrito.getInstancia();
        try {
            com.mycompany.app.Producto p = dao.buscarPorId(4);
            if (p != null) {
                if (carrito.getCantidadProducto(6) + 1 > p.getStock()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "¡Stock agotado!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
                carrito.anadirProducto(p, 1);
                cargarDatosStock();
                javax.swing.JOptionPane.showMessageDialog(this, "Añadido: " + p.getNombre());
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        com.mycompany.app.Carrito carrito = com.mycompany.app.Carrito.getInstancia();

        if (carrito.getListaElementos().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "La cesta está vacía. ¡Añade productos primero!");
        } else {
            //Construimos el texto del ticket
            StringBuilder mensaje = new StringBuilder();
            mensaje.append("=== TU COMPRA ACTUAL ===\n\n");

            for (com.mycompany.app.Carrito.ElementoCarrito item : carrito.getListaElementos()) {
                mensaje.append("• ").append(item.getProducto().getNombre())
                        .append("  (x").append(item.getCantidad()).append(")")
                        .append("  ->  ").append(String.format("%.2f", item.getImporteTotal())).append("€\n");
            }

            mensaje.append("\n========================\n");
            mensaje.append("TOTAL: ").append(String.format("%.2f", carrito.calcularTotal())).append("€");

            //Definimos los botones que queremos que salgan
            Object[] botones = {"Ir a Pagar", "Seguir Comprando"};

            //Mostramos la ventana con opciones
            int opcionElegida = javax.swing.JOptionPane.showOptionDialog(
                    this,
                    mensaje.toString(),
                    "Revisar Cesta",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null,
                    botones,
                    botones[1] // Botón seleccionado por defecto
            );

            //Actuamos según lo que haya pulsado
            if (opcionElegida == 0) {
         
                new Ventana_pago().setVisible(true);
                this.dispose();
            }
            
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_carnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_carnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_carnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_carnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_carnes().setVisible(true);
            }
        });
    }

    private void cargarDatosStock() {
        com.mycompany.dao.ProductoDAO dao = new com.mycompany.dao.ProductoDAO();
        com.mycompany.app.Carrito carrito = com.mycompany.app.Carrito.getInstancia();

        try {
            // ID 4: Ternera
            com.mycompany.app.Producto p4 = dao.buscarPorId(4);
            if (p4 != null) {
                int stock = p4.getStock() - carrito.getCantidadProducto(4);
                lblStockTernera.setText(p4.getNombre() + " - Stock: " + stock);
                if (stock <= 0) {
                    lblStockTernera.setText("AGOTADO");
                    lblStockTernera.setForeground(java.awt.Color.RED);
                } else {
                    lblStockTernera.setForeground(java.awt.Color.BLACK);
                }
            }

            // ID 5: Pollo
            com.mycompany.app.Producto p5 = dao.buscarPorId(5);
            if (p5 != null) {
                int stock = p5.getStock() - carrito.getCantidadProducto(5);
                lblStockPollo.setText(p5.getNombre() + " - Stock: " + stock);
                if (stock <= 0) {
                    lblStockPollo.setText("AGOTADO");
                    lblStockPollo.setForeground(java.awt.Color.RED);
                } else {
                    lblStockPollo.setForeground(java.awt.Color.BLACK);
                }
            }

            // ID 6: Hamburguesa
            com.mycompany.app.Producto p6 = dao.buscarPorId(6);
            if (p6 != null) {
                int stock = p6.getStock() - carrito.getCantidadProducto(6);
                lblStockHamburguesa.setText(p6.getNombre() + " - Stock: " + stock);
                if (stock <= 0) {
                    lblStockHamburguesa.setText("AGOTADO");
                    lblStockHamburguesa.setForeground(java.awt.Color.RED);
                } else {
                    lblStockHamburguesa.setForeground(java.awt.Color.BLACK);
                }
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error stock: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblStockHamburguesa;
    private javax.swing.JLabel lblStockPollo;
    private javax.swing.JLabel lblStockTernera;
    // End of variables declaration//GEN-END:variables
}
